### ISSUE TITLE
Code detail

### ISSUE THREAD

**Issue by whu-lyh** [z619850002/ROECS#1]
Hi Zhang，thanks for your code. i have some misunderstandings as followings and hope to get your reply:
- how to get a svs camera's BEV image?
- inside your code [here](https://github.com/z619850002/ROECS/blob/HEAD/src/optimizer/surround_optimizer.cpp#L374). you call `m_iOptimizer.optimize(10);m_iOptimizer.optimize(100);` is there any difference with directly call `m_iOptimizer.optimize(110)` ?
- and [here](https://github.com/z619850002/ROECS/blob/HEAD/src/optimizer/surround_optimizer.cpp#L296), what is the 23.3 mean and its unit?
- where can i download your supplementary material of paper "ROECS: A Robust Semi-direct Pipeline Towards Online Extrinsics Correction of the Surround-view System"
Thanks again!!

**Comment by z619850002** [comment]
1. Actually, details about how to generate the bird's-eye view image can be found in our supplementary material.
2. Theoretically there is no difference. However, due to the internal implementation details of the g2o, each time you call the optimize, some preparations will be conducted firstly, thus they are a little difference in fact. I found the current implementation is a little better compared with calling the optimization function just once by practice. It's a little complicated to explain, but I believe this doesn't influence the key idea of ROECS. So I think you may just ignore this.
3. 23.3 is the sigma of the huber kernel function. It's just a hyper parameter.
4. These days I will upload the supplementary material to the index page of ROECS.
I wish these could be helpful to you.

**Comment by whu-lyh** [comment]
Well, thanks for your reply.
